// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app_layout from "./routes/(app)/_layout.tsx";
import * as $_app_actions from "./routes/(app)/actions.tsx";
import * as $_app_connections from "./routes/(app)/connections.tsx";
import * as $_app_create from "./routes/(app)/create.tsx";
import * as $_app_dashboard from "./routes/(app)/dashboard.tsx";
import * as $_app_journal_id_ from "./routes/(app)/journal/[id].tsx";
import * as $_app_journal_index from "./routes/(app)/journal/index.tsx";
import * as $_app_mirror from "./routes/(app)/mirror.tsx";
import * as $_app_profile from "./routes/(app)/profile.tsx";
import * as $_app_rooms_id_ from "./routes/(app)/rooms/[id].tsx";
import * as $_app_rooms_index from "./routes/(app)/rooms/index.tsx";
import * as $_app_settings from "./routes/(app)/settings.tsx";
import * as $_app_threads_id_ from "./routes/(app)/threads/[id].tsx";
import * as $_app_threads_index from "./routes/(app)/threads/index.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $auth from "./routes/auth.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Error404 from "./islands/Error404.tsx";
import * as $WalletConnectButton from "./islands/WalletConnectButton.tsx";
import * as $connections_CommunityPulseStripIsland from "./islands/connections/CommunityPulseStripIsland.tsx";
import * as $connections_ConnectionsHub from "./islands/connections/ConnectionsHub.tsx";
import * as $connections_ThoughtStream from "./islands/connections/ThoughtStream.tsx";
import * as $connections_WisdomMap from "./islands/connections/WisdomMap.tsx";
import * as $connections_index from "./islands/connections/index.ts";
import * as $create_CreateHub from "./islands/create/CreateHub.tsx";
import * as $create_index from "./islands/create/index.ts";
import * as $dashboard_DashboardRooms from "./islands/dashboard/DashboardRooms.tsx";
import * as $dashboard_HomeOverview from "./islands/dashboard/HomeOverview.tsx";
import * as $dashboard_PulseHome from "./islands/dashboard/PulseHome.tsx";
import * as $dashboard_index from "./islands/dashboard/index.ts";
import * as $journal_JournalEntryView from "./islands/journal/JournalEntryView.tsx";
import * as $journal_JournalGallery from "./islands/journal/JournalGallery.tsx";
import * as $journal_index from "./islands/journal/index.ts";
import * as $landing_AboutSection from "./islands/landing/AboutSection.tsx";
import * as $landing_DemoVideo from "./islands/landing/DemoVideo.tsx";
import * as $landing_LandingFooter from "./islands/landing/LandingFooter.tsx";
import * as $landing_LandingIsland from "./islands/landing/LandingIsland.tsx";
import * as $landing_LandingPage from "./islands/landing/LandingPage.tsx";
import * as $landing_LedgerSection from "./islands/landing/LedgerSection.tsx";
import * as $landing_SpectralHero from "./islands/landing/SpectralHero.tsx";
import * as $landing_SystemBento from "./islands/landing/SystemBento.tsx";
import * as $landing_index from "./islands/landing/index.ts";
import * as $layout_AppHeader from "./islands/layout/AppHeader.tsx";
import * as $layout_AppLayoutWrapper from "./islands/layout/AppLayoutWrapper.tsx";
import * as $layout_AppMenu from "./islands/layout/AppMenu.tsx";
import * as $layout_index from "./islands/layout/index.ts";
import * as $library_UnifiedVault from "./islands/library/UnifiedVault.tsx";
import * as $mirror_Mirror from "./islands/mirror/Mirror.tsx";
import * as $mirror_index from "./islands/mirror/index.ts";
import * as $modals_AuthModal from "./islands/modals/AuthModal.tsx";
import * as $modals_CaptureModal from "./islands/modals/CaptureModal.tsx";
import * as $modals_CreateRoomModal from "./islands/modals/CreateRoomModal.tsx";
import * as $modals_CreateThreadModal from "./islands/modals/CreateThreadModal.tsx";
import * as $modals_EditRoomModal from "./islands/modals/EditRoomModal.tsx";
import * as $modals_index from "./islands/modals/index.ts";
import * as $navigation_SynthesisEngine from "./islands/navigation/SynthesisEngine.tsx";
import * as $profile_CollectiveProfile from "./islands/profile/CollectiveProfile.tsx";
import * as $profile_ProfileOverlay from "./islands/profile/ProfileOverlay.tsx";
import * as $profile_ProfilePage from "./islands/profile/ProfilePage.tsx";
import * as $profile_index from "./islands/profile/index.ts";
import * as $rooms_RoomInside from "./islands/rooms/RoomInside.tsx";
import * as $rooms_RoomsGallery from "./islands/rooms/RoomsGallery.tsx";
import * as $rooms_index from "./islands/rooms/index.ts";
import * as $settings_PrivacyManager from "./islands/settings/PrivacyManager.tsx";
import * as $settings_Settings from "./islands/settings/Settings.tsx";
import * as $settings_index from "./islands/settings/index.ts";
import * as $threads_ThreadInside from "./islands/threads/ThreadInside.tsx";
import * as $threads_ThreadsGallery from "./islands/threads/ThreadsGallery.tsx";
import * as $threads_index from "./islands/threads/index.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(app)/_layout.tsx": $_app_layout,
    "./routes/(app)/actions.tsx": $_app_actions,
    "./routes/(app)/connections.tsx": $_app_connections,
    "./routes/(app)/create.tsx": $_app_create,
    "./routes/(app)/dashboard.tsx": $_app_dashboard,
    "./routes/(app)/journal/[id].tsx": $_app_journal_id_,
    "./routes/(app)/journal/index.tsx": $_app_journal_index,
    "./routes/(app)/mirror.tsx": $_app_mirror,
    "./routes/(app)/profile.tsx": $_app_profile,
    "./routes/(app)/rooms/[id].tsx": $_app_rooms_id_,
    "./routes/(app)/rooms/index.tsx": $_app_rooms_index,
    "./routes/(app)/settings.tsx": $_app_settings,
    "./routes/(app)/threads/[id].tsx": $_app_threads_id_,
    "./routes/(app)/threads/index.tsx": $_app_threads_index,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/auth.tsx": $auth,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Error404.tsx": $Error404,
    "./islands/WalletConnectButton.tsx": $WalletConnectButton,
    "./islands/connections/CommunityPulseStripIsland.tsx":
      $connections_CommunityPulseStripIsland,
    "./islands/connections/ConnectionsHub.tsx": $connections_ConnectionsHub,
    "./islands/connections/ThoughtStream.tsx": $connections_ThoughtStream,
    "./islands/connections/WisdomMap.tsx": $connections_WisdomMap,
    "./islands/connections/index.ts": $connections_index,
    "./islands/create/CreateHub.tsx": $create_CreateHub,
    "./islands/create/index.ts": $create_index,
    "./islands/dashboard/DashboardRooms.tsx": $dashboard_DashboardRooms,
    "./islands/dashboard/HomeOverview.tsx": $dashboard_HomeOverview,
    "./islands/dashboard/PulseHome.tsx": $dashboard_PulseHome,
    "./islands/dashboard/index.ts": $dashboard_index,
    "./islands/journal/JournalEntryView.tsx": $journal_JournalEntryView,
    "./islands/journal/JournalGallery.tsx": $journal_JournalGallery,
    "./islands/journal/index.ts": $journal_index,
    "./islands/landing/AboutSection.tsx": $landing_AboutSection,
    "./islands/landing/DemoVideo.tsx": $landing_DemoVideo,
    "./islands/landing/LandingFooter.tsx": $landing_LandingFooter,
    "./islands/landing/LandingIsland.tsx": $landing_LandingIsland,
    "./islands/landing/LandingPage.tsx": $landing_LandingPage,
    "./islands/landing/LedgerSection.tsx": $landing_LedgerSection,
    "./islands/landing/SpectralHero.tsx": $landing_SpectralHero,
    "./islands/landing/SystemBento.tsx": $landing_SystemBento,
    "./islands/landing/index.ts": $landing_index,
    "./islands/layout/AppHeader.tsx": $layout_AppHeader,
    "./islands/layout/AppLayoutWrapper.tsx": $layout_AppLayoutWrapper,
    "./islands/layout/AppMenu.tsx": $layout_AppMenu,
    "./islands/layout/index.ts": $layout_index,
    "./islands/library/UnifiedVault.tsx": $library_UnifiedVault,
    "./islands/mirror/Mirror.tsx": $mirror_Mirror,
    "./islands/mirror/index.ts": $mirror_index,
    "./islands/modals/AuthModal.tsx": $modals_AuthModal,
    "./islands/modals/CaptureModal.tsx": $modals_CaptureModal,
    "./islands/modals/CreateRoomModal.tsx": $modals_CreateRoomModal,
    "./islands/modals/CreateThreadModal.tsx": $modals_CreateThreadModal,
    "./islands/modals/EditRoomModal.tsx": $modals_EditRoomModal,
    "./islands/modals/index.ts": $modals_index,
    "./islands/navigation/SynthesisEngine.tsx": $navigation_SynthesisEngine,
    "./islands/profile/CollectiveProfile.tsx": $profile_CollectiveProfile,
    "./islands/profile/ProfileOverlay.tsx": $profile_ProfileOverlay,
    "./islands/profile/ProfilePage.tsx": $profile_ProfilePage,
    "./islands/profile/index.ts": $profile_index,
    "./islands/rooms/RoomInside.tsx": $rooms_RoomInside,
    "./islands/rooms/RoomsGallery.tsx": $rooms_RoomsGallery,
    "./islands/rooms/index.ts": $rooms_index,
    "./islands/settings/PrivacyManager.tsx": $settings_PrivacyManager,
    "./islands/settings/Settings.tsx": $settings_Settings,
    "./islands/settings/index.ts": $settings_index,
    "./islands/threads/ThreadInside.tsx": $threads_ThreadInside,
    "./islands/threads/ThreadsGallery.tsx": $threads_ThreadsGallery,
    "./islands/threads/index.ts": $threads_index,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
