// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app_layout from "./routes/(app)/_layout.tsx";
import * as $_app_actions from "./routes/(app)/actions.tsx";
import * as $_app_ai_analysis from "./routes/(app)/ai-analysis.tsx";
import * as $_app_connections from "./routes/(app)/connections.tsx";
import * as $_app_create from "./routes/(app)/create.tsx";
import * as $_app_dashboard from "./routes/(app)/dashboard.tsx";
import * as $_app_discover from "./routes/(app)/discover.tsx";
import * as $_app_journal_community from "./routes/(app)/journal-community.tsx";
import * as $_app_journal_id_ from "./routes/(app)/journal/[id].tsx";
import * as $_app_journal_index from "./routes/(app)/journal/index.tsx";
import * as $_app_mirror from "./routes/(app)/mirror.tsx";
import * as $_app_profile from "./routes/(app)/profile.tsx";
import * as $_app_profile_userId_ from "./routes/(app)/profile/[userId].tsx";
import * as $_app_rooms_id_ from "./routes/(app)/rooms/[id].tsx";
import * as $_app_rooms_index from "./routes/(app)/rooms/index.tsx";
import * as $_app_settings from "./routes/(app)/settings.tsx";
import * as $_app_streaks from "./routes/(app)/streaks.tsx";
import * as $_app_streaks_index from "./routes/(app)/streaks/index.tsx";
import * as $_app_threads_id_ from "./routes/(app)/threads/[id].tsx";
import * as $_app_threads_index from "./routes/(app)/threads/index.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_ai_socratic from "./routes/api/ai/socratic.ts";
import * as $api_artifacts_ingest_url from "./routes/api/artifacts/ingest-url.ts";
import * as $api_artifacts_upload_document from "./routes/api/artifacts/upload-document.ts";
import * as $api_auth_2fa from "./routes/api/auth/2fa.ts";
import * as $api_auth_demo from "./routes/api/auth/demo.ts";
import * as $api_auth_forgot_password from "./routes/api/auth/forgot-password.ts";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_register from "./routes/api/auth/register.ts";
import * as $api_auth_reset_password from "./routes/api/auth/reset-password.ts";
import * as $api_circles_id_members from "./routes/api/circles/[id]/members.ts";
import * as $api_circles_id_membership from "./routes/api/circles/[id]/membership.ts";
import * as $api_circles_join from "./routes/api/circles/join.ts";
import * as $api_circles_leave from "./routes/api/circles/leave.ts";
import * as $api_community_circles from "./routes/api/community/circles.ts";
import * as $api_community_collaborators from "./routes/api/community/collaborators.ts";
import * as $api_community_stream from "./routes/api/community/stream.ts";
import * as $api_extract from "./routes/api/extract.ts";
import * as $api_followers_follow from "./routes/api/followers/follow.ts";
import * as $api_followers_index from "./routes/api/followers/index.ts";
import * as $api_followers_status from "./routes/api/followers/status.ts";
import * as $api_followers_unfollow from "./routes/api/followers/unfollow.ts";
import * as $api_health_services from "./routes/api/health/services.ts";
import * as $api_items_id_ from "./routes/api/items/[id].ts";
import * as $api_items_index from "./routes/api/items/index.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_journal_id_ from "./routes/api/journal/[id].ts";
import * as $api_journal_index from "./routes/api/journal/index.ts";
import * as $api_mirror from "./routes/api/mirror.ts";
import * as $api_profile_index from "./routes/api/profile/index.ts";
import * as $api_rooms_id_ from "./routes/api/rooms/[id].ts";
import * as $api_rooms_create from "./routes/api/rooms/create.ts";
import * as $api_rooms_index from "./routes/api/rooms/index.ts";
import * as $api_synthesis_create_artifact from "./routes/api/synthesis/create-artifact.ts";
import * as $api_synthesis_parse from "./routes/api/synthesis/parse.ts";
import * as $api_threads_id_ from "./routes/api/threads/[id].ts";
import * as $api_threads_index from "./routes/api/threads/index.ts";
import * as $api_threads_synthesize from "./routes/api/threads/synthesize.ts";
import * as $api_user_change_password from "./routes/api/user/change-password.ts";
import * as $api_user_delete from "./routes/api/user/delete.ts";
import * as $api_user_export from "./routes/api/user/export.ts";
import * as $api_user_settings from "./routes/api/user/settings.ts";
import * as $api_user_streaks from "./routes/api/user/streaks.ts";
import * as $auth from "./routes/auth.tsx";
import * as $dashboard_index from "./routes/dashboard/index.tsx";
import * as $dashboard_rooms_id_ from "./routes/dashboard/rooms/[id].tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $profile_edit from "./routes/profile/edit.ts";
import * as $reset_password from "./routes/reset-password.tsx";
import * as $Error404 from "./islands/Error404.tsx";
import * as $SyncStatusBadge from "./islands/SyncStatusBadge.tsx";
import * as $WalletConnectButton from "./islands/WalletConnectButton.tsx";
import * as $ai_feedback_AIAnalysisDashboard from "./islands/ai-feedback/AIAnalysisDashboard.tsx";
import * as $connections_CommunityPulseStripIsland from "./islands/connections/CommunityPulseStripIsland.tsx";
import * as $connections_ConnectionsHub from "./islands/connections/ConnectionsHub.tsx";
import * as $connections_ThoughtStream from "./islands/connections/ThoughtStream.tsx";
import * as $connections_WisdomMap from "./islands/connections/WisdomMap.tsx";
import * as $connections_index from "./islands/connections/index.ts";
import * as $create_CreateHub from "./islands/create/CreateHub.tsx";
import * as $create_index from "./islands/create/index.ts";
import * as $dashboard_CreateRoomModal from "./islands/dashboard/CreateRoomModal.tsx";
import * as $dashboard_DashboardClientManager from "./islands/dashboard/DashboardClientManager.tsx";
import * as $dashboard_DashboardLayout from "./islands/dashboard/DashboardLayout.tsx";
import * as $dashboard_DashboardRooms from "./islands/dashboard/DashboardRooms.tsx";
import * as $dashboard_HomeOverview from "./islands/dashboard/HomeOverview.tsx";
import * as $dashboard_PulseHome from "./islands/dashboard/PulseHome.tsx";
import * as $dashboard_RoomCard from "./islands/dashboard/RoomCard.tsx";
import * as $dashboard_index_1 from "./islands/dashboard/index.ts";
import * as $journal_CommunityCard from "./islands/journal/CommunityCard.tsx";
import * as $journal_DiscoveryFeed from "./islands/journal/DiscoveryFeed.tsx";
import * as $journal_EntryDetail from "./islands/journal/EntryDetail.tsx";
import * as $journal_ExportModal from "./islands/journal/ExportModal.tsx";
import * as $journal_JournalEntryView from "./islands/journal/JournalEntryView.tsx";
import * as $journal_JournalGallery from "./islands/journal/JournalGallery.tsx";
import * as $journal_LinkedArtifacts from "./islands/journal/LinkedArtifacts.tsx";
import * as $journal_MirrorTimeline from "./islands/journal/MirrorTimeline.tsx";
import * as $journal_SynthesisCard from "./islands/journal/SynthesisCard.tsx";
import * as $journal_SynthesisCreationForm from "./islands/journal/SynthesisCreationForm.tsx";
import * as $journal_UserProfile from "./islands/journal/UserProfile.tsx";
import * as $journal_VaultModal from "./islands/journal/VaultModal.tsx";
import * as $journal_index from "./islands/journal/index.ts";
import * as $landing_BrandModal from "./islands/landing/BrandModal.tsx";
import * as $landing_DemoVideo from "./islands/landing/DemoVideo.tsx";
import * as $landing_LandingFooter from "./islands/landing/LandingFooter.tsx";
import * as $landing_LandingIsland from "./islands/landing/LandingIsland.tsx";
import * as $landing_LandingPage from "./islands/landing/LandingPage.tsx";
import * as $landing_LiveDashboardSimulation from "./islands/landing/LiveDashboardSimulation.tsx";
import * as $landing_SpectralHero from "./islands/landing/SpectralHero.tsx";
import * as $landing_index from "./islands/landing/index.ts";
import * as $layout_AppHeader from "./islands/layout/AppHeader.tsx";
import * as $layout_AppLayoutWrapper from "./islands/layout/AppLayoutWrapper.tsx";
import * as $layout_AppMenu from "./islands/layout/AppMenu.tsx";
import * as $layout_LogoModal from "./islands/layout/LogoModal.tsx";
import * as $layout_SetupBanner from "./islands/layout/SetupBanner.tsx";
import * as $layout_index from "./islands/layout/index.ts";
import * as $library_UnifiedVault from "./islands/library/UnifiedVault.tsx";
import * as $mirror_ActivityHeatmap from "./islands/mirror/ActivityHeatmap.tsx";
import * as $mirror_MilestoneNotification from "./islands/mirror/MilestoneNotification.tsx";
import * as $mirror_Mirror from "./islands/mirror/Mirror.tsx";
import * as $mirror_MirrorDashboard from "./islands/mirror/MirrorDashboard.tsx";
import * as $mirror_MoodDistribution from "./islands/mirror/MoodDistribution.tsx";
import * as $mirror_StreakCard from "./islands/mirror/StreakCard.tsx";
import * as $mirror_index from "./islands/mirror/index.ts";
import * as $modals_AuthModal from "./islands/modals/AuthModal.tsx";
import * as $modals_CaptureModal from "./islands/modals/CaptureModal.tsx";
import * as $modals_ConfirmDeleteModal from "./islands/modals/ConfirmDeleteModal.tsx";
import * as $modals_CreateRoomModal from "./islands/modals/CreateRoomModal.tsx";
import * as $modals_CreateThreadModal from "./islands/modals/CreateThreadModal.tsx";
import * as $modals_EditRoomModal from "./islands/modals/EditRoomModal.tsx";
import * as $modals_TwoFactorModal from "./islands/modals/TwoFactorModal.tsx";
import * as $modals_VaultGateModal from "./islands/modals/VaultGateModal.tsx";
import * as $modals_index from "./islands/modals/index.ts";
import * as $navigation_SynthesisEngine from "./islands/navigation/SynthesisEngine.tsx";
import * as $profile_CollectiveProfile from "./islands/profile/CollectiveProfile.tsx";
import * as $profile_ProfileOverlay from "./islands/profile/ProfileOverlay.tsx";
import * as $profile_ProfilePage from "./islands/profile/ProfilePage.tsx";
import * as $profile_index from "./islands/profile/index.ts";
import * as $rooms_ArtifactUploader from "./islands/rooms/ArtifactUploader.tsx";
import * as $rooms_JournalModal from "./islands/rooms/JournalModal.tsx";
import * as $rooms_RoomClientManager from "./islands/rooms/RoomClientManager.tsx";
import * as $rooms_RoomInside from "./islands/rooms/RoomInside.tsx";
import * as $rooms_RoomsGallery from "./islands/rooms/RoomsGallery.tsx";
import * as $rooms_SynthesisTrigger from "./islands/rooms/SynthesisTrigger.tsx";
import * as $rooms_index from "./islands/rooms/index.ts";
import * as $settings_PrivacyManager from "./islands/settings/PrivacyManager.tsx";
import * as $settings_Settings from "./islands/settings/Settings.tsx";
import * as $settings_index from "./islands/settings/index.ts";
import * as $streaks_StreakHub from "./islands/streaks/StreakHub.tsx";
import * as $threads_ThreadInside from "./islands/threads/ThreadInside.tsx";
import * as $threads_ThreadsGallery from "./islands/threads/ThreadsGallery.tsx";
import * as $threads_index from "./islands/threads/index.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(app)/_layout.tsx": $_app_layout,
    "./routes/(app)/actions.tsx": $_app_actions,
    "./routes/(app)/ai-analysis.tsx": $_app_ai_analysis,
    "./routes/(app)/connections.tsx": $_app_connections,
    "./routes/(app)/create.tsx": $_app_create,
    "./routes/(app)/dashboard.tsx": $_app_dashboard,
    "./routes/(app)/discover.tsx": $_app_discover,
    "./routes/(app)/journal-community.tsx": $_app_journal_community,
    "./routes/(app)/journal/[id].tsx": $_app_journal_id_,
    "./routes/(app)/journal/index.tsx": $_app_journal_index,
    "./routes/(app)/mirror.tsx": $_app_mirror,
    "./routes/(app)/profile.tsx": $_app_profile,
    "./routes/(app)/profile/[userId].tsx": $_app_profile_userId_,
    "./routes/(app)/rooms/[id].tsx": $_app_rooms_id_,
    "./routes/(app)/rooms/index.tsx": $_app_rooms_index,
    "./routes/(app)/settings.tsx": $_app_settings,
    "./routes/(app)/streaks.tsx": $_app_streaks,
    "./routes/(app)/streaks/index.tsx": $_app_streaks_index,
    "./routes/(app)/threads/[id].tsx": $_app_threads_id_,
    "./routes/(app)/threads/index.tsx": $_app_threads_index,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/ai/socratic.ts": $api_ai_socratic,
    "./routes/api/artifacts/ingest-url.ts": $api_artifacts_ingest_url,
    "./routes/api/artifacts/upload-document.ts": $api_artifacts_upload_document,
    "./routes/api/auth/2fa.ts": $api_auth_2fa,
    "./routes/api/auth/demo.ts": $api_auth_demo,
    "./routes/api/auth/forgot-password.ts": $api_auth_forgot_password,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/register.ts": $api_auth_register,
    "./routes/api/auth/reset-password.ts": $api_auth_reset_password,
    "./routes/api/circles/[id]/members.ts": $api_circles_id_members,
    "./routes/api/circles/[id]/membership.ts": $api_circles_id_membership,
    "./routes/api/circles/join.ts": $api_circles_join,
    "./routes/api/circles/leave.ts": $api_circles_leave,
    "./routes/api/community/circles.ts": $api_community_circles,
    "./routes/api/community/collaborators.ts": $api_community_collaborators,
    "./routes/api/community/stream.ts": $api_community_stream,
    "./routes/api/extract.ts": $api_extract,
    "./routes/api/followers/follow.ts": $api_followers_follow,
    "./routes/api/followers/index.ts": $api_followers_index,
    "./routes/api/followers/status.ts": $api_followers_status,
    "./routes/api/followers/unfollow.ts": $api_followers_unfollow,
    "./routes/api/health/services.ts": $api_health_services,
    "./routes/api/items/[id].ts": $api_items_id_,
    "./routes/api/items/index.ts": $api_items_index,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/journal/[id].ts": $api_journal_id_,
    "./routes/api/journal/index.ts": $api_journal_index,
    "./routes/api/mirror.ts": $api_mirror,
    "./routes/api/profile/index.ts": $api_profile_index,
    "./routes/api/rooms/[id].ts": $api_rooms_id_,
    "./routes/api/rooms/create.ts": $api_rooms_create,
    "./routes/api/rooms/index.ts": $api_rooms_index,
    "./routes/api/synthesis/create-artifact.ts": $api_synthesis_create_artifact,
    "./routes/api/synthesis/parse.ts": $api_synthesis_parse,
    "./routes/api/threads/[id].ts": $api_threads_id_,
    "./routes/api/threads/index.ts": $api_threads_index,
    "./routes/api/threads/synthesize.ts": $api_threads_synthesize,
    "./routes/api/user/change-password.ts": $api_user_change_password,
    "./routes/api/user/delete.ts": $api_user_delete,
    "./routes/api/user/export.ts": $api_user_export,
    "./routes/api/user/settings.ts": $api_user_settings,
    "./routes/api/user/streaks.ts": $api_user_streaks,
    "./routes/auth.tsx": $auth,
    "./routes/dashboard/index.tsx": $dashboard_index,
    "./routes/dashboard/rooms/[id].tsx": $dashboard_rooms_id_,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/profile/edit.ts": $profile_edit,
    "./routes/reset-password.tsx": $reset_password,
  },
  islands: {
    "./islands/Error404.tsx": $Error404,
    "./islands/SyncStatusBadge.tsx": $SyncStatusBadge,
    "./islands/WalletConnectButton.tsx": $WalletConnectButton,
    "./islands/ai-feedback/AIAnalysisDashboard.tsx":
      $ai_feedback_AIAnalysisDashboard,
    "./islands/connections/CommunityPulseStripIsland.tsx":
      $connections_CommunityPulseStripIsland,
    "./islands/connections/ConnectionsHub.tsx": $connections_ConnectionsHub,
    "./islands/connections/ThoughtStream.tsx": $connections_ThoughtStream,
    "./islands/connections/WisdomMap.tsx": $connections_WisdomMap,
    "./islands/connections/index.ts": $connections_index,
    "./islands/create/CreateHub.tsx": $create_CreateHub,
    "./islands/create/index.ts": $create_index,
    "./islands/dashboard/CreateRoomModal.tsx": $dashboard_CreateRoomModal,
    "./islands/dashboard/DashboardClientManager.tsx":
      $dashboard_DashboardClientManager,
    "./islands/dashboard/DashboardLayout.tsx": $dashboard_DashboardLayout,
    "./islands/dashboard/DashboardRooms.tsx": $dashboard_DashboardRooms,
    "./islands/dashboard/HomeOverview.tsx": $dashboard_HomeOverview,
    "./islands/dashboard/PulseHome.tsx": $dashboard_PulseHome,
    "./islands/dashboard/RoomCard.tsx": $dashboard_RoomCard,
    "./islands/dashboard/index.ts": $dashboard_index_1,
    "./islands/journal/CommunityCard.tsx": $journal_CommunityCard,
    "./islands/journal/DiscoveryFeed.tsx": $journal_DiscoveryFeed,
    "./islands/journal/EntryDetail.tsx": $journal_EntryDetail,
    "./islands/journal/ExportModal.tsx": $journal_ExportModal,
    "./islands/journal/JournalEntryView.tsx": $journal_JournalEntryView,
    "./islands/journal/JournalGallery.tsx": $journal_JournalGallery,
    "./islands/journal/LinkedArtifacts.tsx": $journal_LinkedArtifacts,
    "./islands/journal/MirrorTimeline.tsx": $journal_MirrorTimeline,
    "./islands/journal/SynthesisCard.tsx": $journal_SynthesisCard,
    "./islands/journal/SynthesisCreationForm.tsx":
      $journal_SynthesisCreationForm,
    "./islands/journal/UserProfile.tsx": $journal_UserProfile,
    "./islands/journal/VaultModal.tsx": $journal_VaultModal,
    "./islands/journal/index.ts": $journal_index,
    "./islands/landing/BrandModal.tsx": $landing_BrandModal,
    "./islands/landing/DemoVideo.tsx": $landing_DemoVideo,
    "./islands/landing/LandingFooter.tsx": $landing_LandingFooter,
    "./islands/landing/LandingIsland.tsx": $landing_LandingIsland,
    "./islands/landing/LandingPage.tsx": $landing_LandingPage,
    "./islands/landing/LiveDashboardSimulation.tsx":
      $landing_LiveDashboardSimulation,
    "./islands/landing/SpectralHero.tsx": $landing_SpectralHero,
    "./islands/landing/index.ts": $landing_index,
    "./islands/layout/AppHeader.tsx": $layout_AppHeader,
    "./islands/layout/AppLayoutWrapper.tsx": $layout_AppLayoutWrapper,
    "./islands/layout/AppMenu.tsx": $layout_AppMenu,
    "./islands/layout/LogoModal.tsx": $layout_LogoModal,
    "./islands/layout/SetupBanner.tsx": $layout_SetupBanner,
    "./islands/layout/index.ts": $layout_index,
    "./islands/library/UnifiedVault.tsx": $library_UnifiedVault,
    "./islands/mirror/ActivityHeatmap.tsx": $mirror_ActivityHeatmap,
    "./islands/mirror/MilestoneNotification.tsx": $mirror_MilestoneNotification,
    "./islands/mirror/Mirror.tsx": $mirror_Mirror,
    "./islands/mirror/MirrorDashboard.tsx": $mirror_MirrorDashboard,
    "./islands/mirror/MoodDistribution.tsx": $mirror_MoodDistribution,
    "./islands/mirror/StreakCard.tsx": $mirror_StreakCard,
    "./islands/mirror/index.ts": $mirror_index,
    "./islands/modals/AuthModal.tsx": $modals_AuthModal,
    "./islands/modals/CaptureModal.tsx": $modals_CaptureModal,
    "./islands/modals/ConfirmDeleteModal.tsx": $modals_ConfirmDeleteModal,
    "./islands/modals/CreateRoomModal.tsx": $modals_CreateRoomModal,
    "./islands/modals/CreateThreadModal.tsx": $modals_CreateThreadModal,
    "./islands/modals/EditRoomModal.tsx": $modals_EditRoomModal,
    "./islands/modals/TwoFactorModal.tsx": $modals_TwoFactorModal,
    "./islands/modals/VaultGateModal.tsx": $modals_VaultGateModal,
    "./islands/modals/index.ts": $modals_index,
    "./islands/navigation/SynthesisEngine.tsx": $navigation_SynthesisEngine,
    "./islands/profile/CollectiveProfile.tsx": $profile_CollectiveProfile,
    "./islands/profile/ProfileOverlay.tsx": $profile_ProfileOverlay,
    "./islands/profile/ProfilePage.tsx": $profile_ProfilePage,
    "./islands/profile/index.ts": $profile_index,
    "./islands/rooms/ArtifactUploader.tsx": $rooms_ArtifactUploader,
    "./islands/rooms/JournalModal.tsx": $rooms_JournalModal,
    "./islands/rooms/RoomClientManager.tsx": $rooms_RoomClientManager,
    "./islands/rooms/RoomInside.tsx": $rooms_RoomInside,
    "./islands/rooms/RoomsGallery.tsx": $rooms_RoomsGallery,
    "./islands/rooms/SynthesisTrigger.tsx": $rooms_SynthesisTrigger,
    "./islands/rooms/index.ts": $rooms_index,
    "./islands/settings/PrivacyManager.tsx": $settings_PrivacyManager,
    "./islands/settings/Settings.tsx": $settings_Settings,
    "./islands/settings/index.ts": $settings_index,
    "./islands/streaks/StreakHub.tsx": $streaks_StreakHub,
    "./islands/threads/ThreadInside.tsx": $threads_ThreadInside,
    "./islands/threads/ThreadsGallery.tsx": $threads_ThreadsGallery,
    "./islands/threads/index.ts": $threads_index,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
