// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app_layout from "./routes/(app)/_layout.tsx";
import * as $_app_actions from "./routes/(app)/actions.tsx";
import * as $_app_connections from "./routes/(app)/connections.tsx";
import * as $_app_create from "./routes/(app)/create.tsx";
import * as $_app_dashboard from "./routes/(app)/dashboard.tsx";
import * as $_app_journal_id_ from "./routes/(app)/journal/[id].tsx";
import * as $_app_journal_index from "./routes/(app)/journal/index.tsx";
import * as $_app_mirror from "./routes/(app)/mirror.tsx";
import * as $_app_profile from "./routes/(app)/profile.tsx";
import * as $_app_rooms_id_ from "./routes/(app)/rooms/[id].tsx";
import * as $_app_rooms_index from "./routes/(app)/rooms/index.tsx";
import * as $_app_settings from "./routes/(app)/settings.tsx";
import * as $_app_threads_id_ from "./routes/(app)/threads/[id].tsx";
import * as $_app_threads_index from "./routes/(app)/threads/index.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $ActiveCircleCard from "./islands/ActiveCircleCard.tsx";
import * as $AppHeader from "./islands/AppHeader.tsx";
import * as $AppLayoutWrapper from "./islands/AppLayoutWrapper.tsx";
import * as $AppMenu from "./islands/AppMenu.tsx";
import * as $AuthModal from "./islands/AuthModal.tsx";
import * as $CaptureModal from "./islands/CaptureModal.tsx";
import * as $CollaboratorCard from "./islands/CollaboratorCard.tsx";
import * as $CommunityPulseStrip from "./islands/CommunityPulseStrip.tsx";
import * as $CommunityRoomCard from "./islands/CommunityRoomCard.tsx";
import * as $ConnectionsHub from "./islands/ConnectionsHub.tsx";
import * as $CreateHub from "./islands/CreateHub.tsx";
import * as $CreateRoomModal from "./islands/CreateRoomModal.tsx";
import * as $CreateThreadModal from "./islands/CreateThreadModal.tsx";
import * as $DashboardRooms from "./islands/DashboardRooms.tsx";
import * as $DashboardWidgets from "./islands/DashboardWidgets.tsx";
import * as $EditRoomModal from "./islands/EditRoomModal.tsx";
import * as $HomeOverview from "./islands/HomeOverview.tsx";
import * as $JournalEntryView from "./islands/JournalEntryView.tsx";
import * as $JournalGallery from "./islands/JournalGallery.tsx";
import * as $LandingFeatures from "./islands/LandingFeatures.tsx";
import * as $LandingHero from "./islands/LandingHero.tsx";
import * as $LandingIsland from "./islands/LandingIsland.tsx";
import * as $LandingPage from "./islands/LandingPage.tsx";
import * as $Mirror from "./islands/Mirror.tsx";
import * as $PortraitCard from "./islands/PortraitCard.tsx";
import * as $PrivacyBadge from "./islands/PrivacyBadge.tsx";
import * as $PrivacyManager from "./islands/PrivacyManager.tsx";
import * as $ProfileOverlay from "./islands/ProfileOverlay.tsx";
import * as $ProfilePage from "./islands/ProfilePage.tsx";
import * as $RoomInside from "./islands/RoomInside.tsx";
import * as $RoomsGallery from "./islands/RoomsGallery.tsx";
import * as $Settings from "./islands/Settings.tsx";
import * as $SharedThemeCluster from "./islands/SharedThemeCluster.tsx";
import * as $ThoughtfulComposer from "./islands/ThoughtfulComposer.tsx";
import * as $ThreadInside from "./islands/ThreadInside.tsx";
import * as $ThreadsGallery from "./islands/ThreadsGallery.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(app)/_layout.tsx": $_app_layout,
    "./routes/(app)/actions.tsx": $_app_actions,
    "./routes/(app)/connections.tsx": $_app_connections,
    "./routes/(app)/create.tsx": $_app_create,
    "./routes/(app)/dashboard.tsx": $_app_dashboard,
    "./routes/(app)/journal/[id].tsx": $_app_journal_id_,
    "./routes/(app)/journal/index.tsx": $_app_journal_index,
    "./routes/(app)/mirror.tsx": $_app_mirror,
    "./routes/(app)/profile.tsx": $_app_profile,
    "./routes/(app)/rooms/[id].tsx": $_app_rooms_id_,
    "./routes/(app)/rooms/index.tsx": $_app_rooms_index,
    "./routes/(app)/settings.tsx": $_app_settings,
    "./routes/(app)/threads/[id].tsx": $_app_threads_id_,
    "./routes/(app)/threads/index.tsx": $_app_threads_index,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ActiveCircleCard.tsx": $ActiveCircleCard,
    "./islands/AppHeader.tsx": $AppHeader,
    "./islands/AppLayoutWrapper.tsx": $AppLayoutWrapper,
    "./islands/AppMenu.tsx": $AppMenu,
    "./islands/AuthModal.tsx": $AuthModal,
    "./islands/CaptureModal.tsx": $CaptureModal,
    "./islands/CollaboratorCard.tsx": $CollaboratorCard,
    "./islands/CommunityPulseStrip.tsx": $CommunityPulseStrip,
    "./islands/CommunityRoomCard.tsx": $CommunityRoomCard,
    "./islands/ConnectionsHub.tsx": $ConnectionsHub,
    "./islands/CreateHub.tsx": $CreateHub,
    "./islands/CreateRoomModal.tsx": $CreateRoomModal,
    "./islands/CreateThreadModal.tsx": $CreateThreadModal,
    "./islands/DashboardRooms.tsx": $DashboardRooms,
    "./islands/DashboardWidgets.tsx": $DashboardWidgets,
    "./islands/EditRoomModal.tsx": $EditRoomModal,
    "./islands/HomeOverview.tsx": $HomeOverview,
    "./islands/JournalEntryView.tsx": $JournalEntryView,
    "./islands/JournalGallery.tsx": $JournalGallery,
    "./islands/LandingFeatures.tsx": $LandingFeatures,
    "./islands/LandingHero.tsx": $LandingHero,
    "./islands/LandingIsland.tsx": $LandingIsland,
    "./islands/LandingPage.tsx": $LandingPage,
    "./islands/Mirror.tsx": $Mirror,
    "./islands/PortraitCard.tsx": $PortraitCard,
    "./islands/PrivacyBadge.tsx": $PrivacyBadge,
    "./islands/PrivacyManager.tsx": $PrivacyManager,
    "./islands/ProfileOverlay.tsx": $ProfileOverlay,
    "./islands/ProfilePage.tsx": $ProfilePage,
    "./islands/RoomInside.tsx": $RoomInside,
    "./islands/RoomsGallery.tsx": $RoomsGallery,
    "./islands/Settings.tsx": $Settings,
    "./islands/SharedThemeCluster.tsx": $SharedThemeCluster,
    "./islands/ThoughtfulComposer.tsx": $ThoughtfulComposer,
    "./islands/ThreadInside.tsx": $ThreadInside,
    "./islands/ThreadsGallery.tsx": $ThreadsGallery,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
