import * as Icons from "lucide-preact";

const features = [
  {
    title: "Sovereign Rooms",
    desc:
      "Isolated cognitive environments. Customize, add artifacts, and let the real-time AI engine analyze patterns within your specific context.",
    icon: Icons.LayoutGrid,
    color: "text-cyan-400",
    bg: "bg-cyan-500/5 hover:bg-cyan-500/10",
    border: "border-cyan-500/20 hover:border-cyan-400",
  },
  {
    title: "Synthesis Threads",
    desc:
      "Real-time AI analysis. Threads detect patterns in your input, generating blueprints with live AI scoring.",
    icon: Icons.GitBranch,
    color: "text-purple-400",
    bg: "bg-purple-500/5 hover:bg-purple-500/10",
    border: "border-purple-500/20 hover:border-purple-400",
  },
  {
    title: "The Journal",
    desc:
      "A terminal for contemplation. Journal on curated content or start fresh. AI asks Socratic questions as you type.",
    icon: Icons.PenTool,
    color: "text-emerald-400",
    bg: "bg-emerald-500/5 hover:bg-emerald-500/10",
    border: "border-emerald-500/20 hover:border-emerald-400",
  },
  {
    title: "Global Community",
    desc:
      "Publish synthesized thoughts. Connect with other minds and watch ideas compound across the network.",
    icon: Icons.Globe2,
    color: "text-blue-400",
    bg: "bg-blue-500/5 hover:bg-blue-500/10",
    border: "border-blue-500/20 hover:border-blue-400",
  },
  {
    title: "Cognitive Mirror",
    desc:
      "A reflection of your growth. Visualize your intellectual journey and track synthesis rates.",
    icon: Icons.ScanFace,
    color: "text-pink-400",
    bg: "bg-pink-500/5 hover:bg-pink-500/10",
    border: "border-pink-500/20 hover:border-pink-400",
  },
  {
    title: "Collective Intelligence",
    desc:
      "The network effect of thought. Discover emerging patterns generated by the combined insights of the ecosystem.",
    icon: Icons.Network,
    color: "text-amber-400",
    bg: "bg-amber-500/5 hover:bg-amber-500/10",
    border: "border-amber-500/20 hover:border-amber-400",
  },
  {
    title: "Encrypted Vault",
    desc:
      "Your thoughts remain yours through blockchain technology. Immutable provenance guarantees ownership forever.",
    icon: Icons.Lock,
    color: "text-red-400",
    bg: "bg-red-500/5 hover:bg-red-500/10",
    border: "border-red-500/20 hover:border-red-400",
  },
];

export default function SystemBento() {
  return (
    <section className="relative py-16 px-4 md:px-16 max-w-[1800px] mx-auto overflow-hidden">
      <div className="mb-8 px-6">
        <h2 className="text-[9px] font-bold uppercase tracking-[0.4em] text-[var(--muse-muted)] mb-2 flex items-center gap-2">
          <Icons.Workflow size={10} /> The Ecosystem
        </h2>
        <h3 className="text-2xl md:text-3xl font-bold tracking-tight text-[var(--muse-text)] leading-tight">
          Engineered for{" "}
          <span className="font-serif italic text-[var(--muse-muted)]">
            Intention.
          </span>
        </h3>
      </div>

      <div className="relative overflow-hidden w-full pb-6 pt-2 group">
        <div className="absolute left-0 top-0 bottom-0 w-20 bg-gradient-to-r from-[var(--muse-bg)] to-transparent z-10 pointer-events-none" />
        <div className="absolute right-0 top-0 bottom-0 w-20 bg-gradient-to-l from-[var(--muse-bg)] to-transparent z-10 pointer-events-none" />

        <div className="flex gap-4 w-max animate-ping-pong group-hover:[animation-play-state:paused] px-[8vw]">
          {features.map((f, i) => (
            <div
              key={`${f.title}-${i}`}
              className={`group/card relative overflow-hidden rounded-2xl border ${f.border} ${f.bg} p-6 transition-all hover:-translate-y-1.5 hover:shadow-[0_10px_25px_-8px_rgba(0,0,0,0.15)] duration-500 w-[280px] flex-shrink-0 cursor-pointer`}
            >
              <div className="absolute top-0 right-0 p-4 opacity-5 group-hover/card:opacity-10 transition-opacity duration-500">
                <f.icon size={80} strokeWidth={0.5} className={f.color} />
              </div>

              <div className="relative z-10 flex flex-col h-full justify-between gap-8">
                <div
                  className={`w-9 h-9 rounded-lg bg-[var(--muse-surface)]/50 backdrop-blur-md border border-[var(--muse-border)] flex items-center justify-center ${f.color} group-hover/card:scale-105 transition-transform duration-500`}
                >
                  <f.icon size={18} strokeWidth={1.5} />
                </div>

                <div>
                  <h4 className="text-base font-bold text-[var(--muse-text)] mb-2 tracking-tight">
                    {f.title}
                  </h4>
                  <p className="text-[var(--muse-muted)] font-serif italic text-xs leading-relaxed group-hover/card:text-[var(--muse-text)] transition-colors duration-500">
                    {f.desc}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      <style>
        {`
          @keyframes ping-pong {
            0% { transform: translateX(0%); }
            100% { transform: translateX(calc(-100% + 100vw)); }
          }
          .animate-ping-pong {
            animation: ping-pong 25s ease-in-out infinite alternate;
          }
        `}
      </style>
    </section>
  );
}
